default_stages: [commit]
default_language_version:
  python: python3
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: [
        --max-line-length=80
      ]
      exclude: ^(.venv)
      types: ['python']